### ISSUE TITLE
[UI] Add click on space for close pop-up

### ISSUE THREAD

**Issue by Drsheppard01** [xplshn/aZillionAppBundles#11]
Clicking on an empty space is an obvious action to close any pop-up, I think it's worth implementing it

**Comment by xplshn** [comment]
Working on this right now, thanks for the suggestion

**Comment by xplshn** [comment]
Done(https://github.com/xplshn/AppBundleHUB/commit/a5d09c880f90f9c30d338a8e8d4123b8ebc02296)
