### ISSUE TITLE
how to use `mpv --player-operation-mode=cplayer` from terminal? default

### ISSUE THREAD

**Issue by candrapersada** [xplshn/aZillionAppBundles#12]
how to use `mpv --player-operation-mode=cplayer` from terminal?
mpv.dwfs.appbundle

**Comment by xplshn** [comment]
> how to use `mpv --player-operation-mode=cplayer` from terminal? mpv.dwfs.appbundle

I'm not sure what you mean, you can pass this argument just fine to the AppBundle.

Or do you want this mode to be the default?

**Comment by candrapersada** [comment]
> Or do you want this mode to be the default?

Yes if use terminal
mpv by default uses cplayer when using terminal

**Comment by xplshn** [comment]
> > Or do you want this mode to be the default?
> 
> Yes if use terminal mpv by default uses cplayer when using terminal

Actually, I don't compile MPV, I only package it. You should ask that here: https://github.com/pkgforge-dev/mpv-AppImage.git
